#!/usr/bin/env node
const { prepareForElasticSearch } = require("../lib/index");

(async function() {
  const input = process.argv[2];
  if (!input) throw new Error(`Please specify input file: ${process.argv}`);

  const output = process.argv[3];
  if (!output) throw new Error(`Please specify output file: ${process.argv}`);

  console.log("Processing:");
  console.log(`   Input: ${input}`);
  console.log(`  Output: ${output}`);

  await prepareForElasticSearch(input, output);
})().catch(err => {
  console.error(err);
  process.exit(-1);
});
